create database clinica_veterinaria 
CREATE TABLE CLIENTE (
 CPF VARCHAR(11) PRIMARY KEY,
 Nome VARCHAR(50) NOT NULL,
 Telefone VARCHAR(15)
);
CREATE TABLE VETERINARIO (
 CRMV VARCHAR(10) PRIMARY KEY,
 Nome VARCHAR(50) NOT NULL,
 Dt_Admissao DATE NOT NULL,
 Salario DECIMAL(10,2) NOT NULL
);
CREATE TABLE ANIMAL (
 Codigo INT PRIMARY KEY,
 Nome VARCHAR(50) NOT NULL,
 Ano_Nasc INT NOT NULL,
 Raca VARCHAR(30),
 CPF VARCHAR(11) NOT NULL,
 FOREIGN KEY (CPF) REFERENCES CLIENTE(CPF)
);
CREATE TABLE CONSULTA (
 IDConsulta INT PRIMARY KEY,
 Data DATE NOT NULL,
 Hora TIME NOT NULL,
 Motivo VARCHAR(100),
 CRMV VARCHAR(10) NOT NULL,
 Codigo INT NOT NULL,
 FOREIGN KEY (CRMV) REFERENCES VETERINARIO(CRMV),
 FOREIGN KEY (Codigo) REFERENCES ANIMAL(Codigo)
);